### ISSUE TITLE
No product id

### ISSUE THREAD

**Issue by ssj1053** [signalpoint/commerce#12]
Hi there,

I'm newbie on drupalgap programming. I've followed most of the tutorials posted and they were  perfectly understandable, never had any problem. But this time, while trying to make "Build a Mobile App to Sell Products with Drupal" from (http://tylerfrankenstein.com/code/build-mobile-app-sell-products-with-drupal), I've got some problems that I can't solve.

When we display the products list, we get this message at the console:

WARNING: theme_view() - No id specified on attributes! A random id will be generated instead.

Later when we press the "add to cart" button:

WARNING: drupalgap_entity_get_core_fields - Unknown anonymous comment setting (beer): 0
drupalgap-7.x-1.3.min.js:175 WARNING: theme_undefined() does not exist. Called by: drupalgap_render_page().

WARNING: _commerce_line_item_add_to_order - no product_id

We have tried many ways to solve it (dpms, fields, changing our drupal views etc) but it has been impossible to fix it.

Any help would be greatfully welcome. Here are some screenshots from our console:

![image](https://cloud.githubusercontent.com/assets/16242599/12624672/81813a18-c530-11e5-967c-37e2ecf15eaa.png)

![image](https://cloud.githubusercontent.com/assets/16242599/12624686/94663ffc-c530-11e5-8a6a-aec426fb43a8.png)

![image](https://cloud.githubusercontent.com/assets/16242599/12624694/a3fe2ff6-c530-11e5-8ce1-dce735478819.png)

![image](https://cloud.githubusercontent.com/assets/16242599/12624703/abff991a-c530-11e5-9177-fa118ba8f4b8.png)

![image](https://cloud.githubusercontent.com/assets/16242599/12624709/b60c3ac6-c530-11e5-98f3-5e4bcd0620e6.png)

![image](https://cloud.githubusercontent.com/assets/16242599/12624719/c1489a6a-c530-11e5-99bb-8e8215a561d7.png)

**Comment by signalpoint** [comment]
@ssj1053 Thank you for the thorough debugging and screenshots. I have committed a fix for the `WARNING: _commerce_line_item_add_to_order - no product_id`, please create separate issues for any remaining problems.
